language: ruby
branches:
  only:
  - master
rvm:
- 2.0.0
install:
- rake bootstrap
script:
- rake deploy
env:
  global:
    secure: T1RQed2lnT+z8acmo4YzIk1wC8twja0DSuV539wueqFsCU1baJpTejQLkuk/JI5bLulroroncSFc2nWxd7HK0+cqEAVumsiho8kEMCXkyYiXvCZlUsPmzpWvUmnVRCoXMYHcrTAAN7tQOumOAPrq3Yx0lkBYeeQOC1jWeadIYeU=
