name: CocoaPods Blog
markdown: redcarpet
pygments: true
permalink: /:month-:day-:year/:title
exclude: ['Gemfile*', 'rakefile.rb', 'README.md', 'shared']
paginate: 5

authors:
  keith:
    name: Keith Smiley
    twitter: SmileyKeith
    gravatar: 6ab7ae85b84ebb323fab427b11500742
  orta:
    name: Orta Therox
    twitter: orta
    gravatar: f116cb3be23153ec08b94e8bd4dbcfeb
